# Generated by Django 4.1.6 on 2023-02-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('calories', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('U', 'unhealthy'), ('H', 'healthy')], default='healthy', max_length=250)),
            ],
        ),
    ]
